// PROBABILIDAD DE QUE APAREZCA EL EASTER EGG (1 ENTRE 999)
export const PROBABILIDAD_EASTER_EGG = 1 / 999

// DURACIÓN DEL EASTER EGG EN MS (~1 VUELTA DEL GIF: 21 CUADROS x 120 MS, REDONDEADA)
export const DURACION_EASTER_EGG_MS = 3000
